### ISSUE TITLE
你删了一些方法？

### ISSUE THREAD

**Issue by AreYReady** [CListery/BottomNavigationEx#1]
<img width="841" alt="image" src="https://user-images.githubusercontent.com/13625746/179166605-55b7a414-bc09-43c6-a475-1bed8bb7a945.png">

**Comment by CListery** [comment]
readme改漏了，
enableShiftingMode -> enableLabelVisibility
enableItemShiftingMode -> enableItemHorizontalTranslation
setOnNavigationItemSelectedListener -> setMenuListener
