### ISSUE TITLE
怎么只有选中的Menu才显示文字内容，没选中的只有icon

### ISSUE THREAD

**Issue by gjmm123** [CListery/BottomNavigationEx#10]

**Comment by CListery** [comment]
贴一下你的代码

**Comment by gjmm123** [comment]
![image](https://user-images.githubusercontent.com/48173775/229031429-2eea1a62-b961-40a0-b2ba-b028795648a4.png)
![image](https://user-images.githubusercontent.com/48173775/229031481-62a30936-5c80-4fa0-909d-4f250e3048d1.png)
![image](https://user-images.githubusercontent.com/48173775/229031531-12e8ff73-ac69-4bc1-a020-58cbdc240c94.png)
![image](https://user-images.githubusercontent.com/48173775/229031588-0406fd57-48f8-4f14-b777-9bbfde8953b5.png)
kotlin 的

**Comment by CListery** [comment]
依赖版本

**Comment by gjmm123** [comment]
![image](https://user-images.githubusercontent.com/48173775/229037113-bb54c91a-0646-4871-a0a3-555521923854.png)
![image](https://user-images.githubusercontent.com/48173775/229037157-38b96382-0c04-4b47-a28f-2ad58b2f5d4f.png)

**Comment by CListery** [comment]
通过以下 API 禁用 label 的可见性切换

enableLabelVisibility(false)

**Comment by gjmm123** [comment]
好的，可以了，但是切换的时候文字会稍微左右抖动一下，这是专门做的动画效果吗？可以禁止么？

**Comment by CListery** [comment]
看文档了吗？看demo了吗？这些基本上都有答案的

enableAnimation(false)

**Comment by CListery** [comment]
https://github.com/CListery/BottomNavigationEx/blob/master/doc/API-zh-cn.md

**Comment by gjmm123** [comment]
好的，谢谢了
