### ISSUE TITLE
demo跑不起来很头大

### ISSUE THREAD

**Issue by zs1973** [CListery/BottomNavigationEx#11]
Build file '/Users/zs/Downloads/BottomNavigationEx-master/lib_bottomnavigation_13x/build.gradle.kts' line: 3

An exception occurred applying plugin request [id: 'kre-publish']
> Failed to apply plugin 'publish'.
   > Cannot get non-null property 'sonatypeRepoRelease' on project ':lib_bottomnavigation_13x' as it does not exist

* Try:
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

**Comment by CListery** [comment]
我猜你肯定把这一行的注释打开了
```gradle
implementation(project(mapOf("path" to ":lib_bottomnavigation_13x")))
```
！！！请不要使用项目类模块的依赖方式，他会去自动检查一些用于发布的gradle脚本

请使用maven中央仓库的依赖方式
```gradle
    // material 1.7.x
    implementation(libs.material170)
    implementation(lib_17x)
```

**Comment by zs1973** [comment]
没有 我把maven发布相关的注释掉就跑起来了
