### ISSUE TITLE
动画失效

### ISSUE THREAD

**Issue by KnightAndroid** [CListery/BottomNavigationEx#16]
给导航栏设置动画会失效。显示隐藏也不成功，版本：2.0.0

**Comment by CListery** [comment]
@KnightAndroid 试过直接运行项目中的demo了吗？demo是否有同样问题？

**Comment by KnightAndroid** [comment]
> @KnightAndroid 试过直接运行项目中的demo了吗？demo是否有同样问题？

我是说整个导航下移或者上移动或者整个导航栏隐藏都没反应

**Comment by CListery** [comment]
@KnightAndroid 额，没太懂你的意思，你指的是直接给整个导航栏加动画？可以贴一下具体的代码吗

**Comment by KnightAndroid** [comment]
> @KnightAndroid 额，没太懂你的意思，你指的是直接给整个导航栏加动画？可以贴一下具体的代码吗

就是我在页面 一个按钮在中间， 底部是一个导航栏，我点击按钮 给导航栏上移和下移都不成功 ，不知道为何 其他得view就可以，不知道是不是库的影响？

**Comment by CListery** [comment]
@KnightAndroid  你具体操作的view是哪个？是BottomNavigationViewEx还是getRealView()之后的view？最好贴一下代码，我帮你看看

**Comment by KnightAndroid** [comment]
> @KnightAndroid 你具体操作的view是哪个？是BottomNavigationViewEx还是getRealView()之后的view？最好贴一下代码，我帮你看看
简单代码如下：
            outAnimator?.let {
                if (!it.isRunning && child.translationY <= 0) {
                    it.start()
                }
            } ?:run{
                outAnimator =
                    ObjectAnimator.ofFloat(child, "translationY", 0f, child.height.toFloat())
                outAnimator?.setDuration(200)
            }

**Comment by KnightAndroid** [comment]
> > @KnightAndroid 你具体操作的view是哪个？是BottomNavigationViewEx还是getRealView()之后的view？最好贴一下代码，我帮你看看
> > 简单代码如下：
> > outAnimator?.let {
> > if (!it.isRunning && child.translationY <= 0) {
> > it.start()
> > }
> > } ?:run{
> > outAnimator =
> > ObjectAnimator.ofFloat(child, "translationY", 0f, child.height.toFloat())
> > outAnimator?.setDuration(200)
> > }

child是BottomNavigationViewEx 这个view

**Comment by CListery** [comment]
你试一下改成这样有没有效果
```kotlin
ObjectAnimator.ofFloat(child, "translationY", 0f, child.getRealView().height.toFloat())
```

**Comment by KnightAndroid** [comment]
> 你试一下改成这样有没有效果
> 
> ```kotlin
> ObjectAnimator.ofFloat(child, "translationY", 0f, child.realView.height.toFloat())
> ```

好的 我试一下

**Comment by KnightAndroid** [comment]
> 忘了改前面的，第一个参数也需要加上 `realView`

知道，我迟点再看

**Comment by CListery** [comment]
demo 已更新 https://github.com/CListery/BottomNavigationEx/commit/958168c5b2c5197a9f9f95daa67b124ae021bb88

**Comment by KnightAndroid** [comment]
> demo 已更新 [958168c](https://github.com/CListery/BottomNavigationEx/commit/958168c5b2c5197a9f9f95daa67b124ae021bb88)

开启动画的时候报错 我这边项目是viewBinding的 报这个view  java.lang.NoSuchFieldException: No field mBinding in class Lcom/xxx/xxx/xxx/activity/MainActivity; (declaration of 'com.xxx.xxx.xxx.activity.MainActivity' appears in /data/app/com.xxx.xxxx.xxx-eBMLgH7XW6fddbZS93XzWg==/base.apk!classes2.dex)

**Comment by CListery** [comment]
@KnightAndroid 还有任何关于该issue的更新吗？

**Comment by KnightAndroid** [comment]
> @KnightAndroid 还有任何关于该issue的更新吗？

没了，关闭这个issue吧
