### ISSUE TITLE
不在xml里面设置app:menu, 可以代码上动态去增加menu么

### ISSUE THREAD

**Issue by zhujinsheng** [CListery/BottomNavigationEx#18]
大佬，我这边想根据接口返回来的配置来控制tab的多少，和文字图片显示：不在xml里面设置app:menu, 可以代码上动态去增加menu么

**Comment by CListery** [comment]
这个项目只是扩展了原生 BNV 的 API，原生 BNV 并没有动态菜单相关的 API，不过可以视为这是一个需求，通过反射修改 BNV 内部的 Menu items 有可能可以实现，后面有时间研究下

**Comment by zhujinsheng** [comment]
> 这个项目只是扩展了原生 BNV 的 API，原生 BNV 并没有动态菜单相关的 API，不过可以视为这是一个需求，通过反射修改 BNV 内部的 Menu items 有可能可以实现，后面有时间研究下

辛苦大佬了

**Comment by CListery** [comment]
`2.2.0` 版本已支持
