### ISSUE TITLE
.enableAnimation(false); 报错

### ISSUE THREAD

**Issue by AreYReady** [CListery/BottomNavigationEx#2]
使用 `mBnve.enableAnimation(false);` 关掉动画，报下面错误。
原想进一步测试下，在你项目里运行下demo看看，下载代码无法正常编译。无果。
<img width="1792" alt="image" src="https://user-images.githubusercontent.com/13625746/184603693-4ec7d99d-4b0e-448c-8078-c52fbe25b63e.png">

**Comment by CListery** [comment]
@AreYReady 请确认你的代码处于master分支的最新
且 model 层 build.gradle 已有
```gradle
dependencies {
    implementation("io.github.clistery:appbasic:1.0.1")
}
```
请在之后再次确认已有以下依赖库引入
![image](https://user-images.githubusercontent.com/13373526/184758806-763ae8e9-78a9-4589-ae5a-c7764d953213.png)

**Comment by AreYReady** [comment]
@CListery implementation("io.github.clistery:appbasic:1.0.1") 增加了这个可以了。我觉得你不需要把你的库弄成这个过得impl 来引入，可以整理下。130 和140的命名方式很奇怪。原[BottomNavigationEx]的库已确定在31不能使用，势必会引流到你这个类似的库。另外，源码还是运行不起来。找到不到某个库，不确定是科学上网原因，还是需要在阿里源。没有做测试了。报错给你看下。
<img width="1026" alt="image" src="https://user-images.githubusercontent.com/13625746/184782633-443470a4-6448-4dba-9848-ce292dd492b4.png">

**Comment by CListery** [comment]
1. appbasic 这个库是我的一个工具库，抽离了很多公共代码，一开始是直接通过 api 的方式引入，但是考虑到有部分用户（目前可能只有我自己 XD）可能会使用不同的版本，所以采用了 impl 的方式
2. 130 对应 material 1.4.0 以下的版本，140 对应 1.4.0 以上版本（后期如果我有时间可能会扩展官方库的 1.5.0\1.6.0\1.7.0...），由于 material 1.4.0 官方库改动较大，所以将对应的版本做成不同的库来分开官方版本，再有就是很好的避免版本依赖冲突，同时可以做到一目了然的版本管理
3. 编译提示找不到依赖库，我估计是你的网络原因，你可以试试直接访问以下链接看能不能下载文件，如果不行，那。。。爱莫能助
```
https://repo1.maven.org/maven2/org/jetbrains/kotlin/kotlin-compiler-embeddable/1.4.31/kotlin-compiler-embeddable-1.4.31.jar
```

**Comment by AreYReady** [comment]
了解，这个问题我关了。
