### ISSUE TITLE
setOnNavigationItemSelectedListener老库的这个方法怎么没有了

### ISSUE THREAD

**Issue by OkamiyGit** [CListery/BottomNavigationEx#3]
我用的之前的老库，升级最新版本发现有问题，用你这个库，但是找不到这个方法了，求解

**Comment by CListery** [comment]
这个库是扩展于之前的库，很多地方都是重构过的，自然API也有一定的差异，现在点击事件监听相关的方法使用 setMenuListener ，文档里面也有写明
