### ISSUE TITLE
遇到了InflateException报错，不知道其他人遇到过没

### ISSUE THREAD

**Issue by zhangjianzhu** [CListery/BottomNavigationEx#4]
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.ishanhu.ecoa/com.ishanhu.ecoa.MainActivity}: android.view.InflateException: Binary XML file line #14: Binary XML file line #27: Binary XML file line #27: Error inflating class com.yh.bottomnavigationex.BottomNavigationViewEx
![image](https://user-images.githubusercontent.com/18592113/200278497-8f682980-d029-4ce7-bd43-73cbbde94a64.png)

**Comment by CListery** [comment]
@zhangjianzhu 可以把报错的 material 库版本贴一下，我有时间会做适配

**Comment by zhangjianzhu** [comment]
> @zhangjianzhu 可以把报错的 material 库版本贴一下，我有时间会做适配

就最新的1.7.0

**Comment by zhangjianzhu** [comment]
@CListery 一开始是material 1.7.0，后面试了1.6.0 和 1.5.0 都不行呢

**Comment by CListery** [comment]
增加 1.5.0 ~ 1.7.0 支持 31fad9e997c8d4cad35fc33533749f54d34982e2
