### ISSUE TITLE
能否支持自定义布局

### ISSUE THREAD

**Issue by AndroidMrYang** [CListery/BottomNavigationEx#5]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by CListery** [comment]
能具体讲一下你的自定义是指什么？

**Comment by AndroidMrYang** [comment]
自定义tab布局  图片替换成lotttieView 加载json动画之类的
