### ISSUE TITLE
想问下这个集成后是什么问题

### ISSUE THREAD

**Issue by AndersonCodeArt** [CListery/BottomNavigationEx#7]
![Uploading image.png…]()

* What went wrong:
Execution failed for task ':app:kaptGenerateStubsBuildDebugKotlin'.
> Error while evaluating property 'filteredArgumentsMap' of task ':app:kaptGenerateStubsBuildDebugKotlin'
   > Could not resolve all files for configuration ':app:buildDebugCompileClasspath'.
      > Failed to transform bottomnavigationex-17x-2.0.0.jar (io.github.clistery:bottomnavigationex-17x:2.0.0) to match attributes {artifactType=android-classes-jar, org.gradle.category=library, org.gradle.libraryelements=jar, org.gradle.status=release, org.gradle.usage=java-api}.
         > Could not find bottomnavigationex-17x-2.0.0.jar (io.github.clistery:bottomnavigationex-17x:2.0.0).
           Searched in the following locations:
               https://maven.aliyun.com/repository/public/io/github/clistery/bottomnavigationex-17x/2.0.0/bottomnavigationex-17x-2.0.0.jar
      > Failed to transform bottomnavigationex-ex-2.0.0.jar (io.github.clistery:bottomnavigationex-ex:2.0.0) to match attributes {artifactType=android-classes-jar, org.gradle.category=library, org.gradle.libraryelements=jar, org.gradle.status=release, org.gradle.usage=java-api}.
         > Could not find bottomnavigationex-ex-2.0.0.jar (io.github.clistery:bottomnavigationex-ex:2.0.0).
           Searched in the following locations:
               https://maven.aliyun.com/repository/public/io/github/clistery/bottomnavigationex-ex/2.0.0/bottomnavigationex-ex-2.0.0.jar
      > Failed to transform bottomnavigationex-base-2.0.0.jar (io.github.clistery:bottomnavigationex-base:2.0.0) to match attributes {artifactType=android-classes-jar, org.gradle.category=library, org.gradle.libraryelements=jar, org.gradle.status=release, org.gradle.usage=java-api}.
         > Could not find bottomnavigationex-base-2.0.0.jar (io.github.clistery:bottomnavigationex-base:2.0.0).
           Searched in the following locations:
               https://maven.aliyun.com/repository/public/io/github/clistery/bottomnavigationex-base/2.0.0/bottomnavigationex-base-2.0.0.jar

**Comment by CListery** [comment]
仅在中央仓库发布

**Comment by AndersonCodeArt** [comment]
OK
